# 서버 포트
server:
  port: 8009

spring:
  jpa:
    show-sql: true     # 콘솔에 JPA 실행 쿼리 출력
    generate-ddl: true # Entity 어노테이션 클래스의 ddl 생성 후 실행
    database: MYSQL
  profiles:
    include:
      - database
      - security

springdoc:
  swagger-ui:
    groups-order: desc # 각 API 그룹의 표시 순서 (path-query-body-response 순서)
    tags-sorter: alpha # 태그 정렬 순서 (alpha/method)
    operations-sorter: method # 컨트롤러 정렬 순서 (delete-get-patch-post-put 순서)
    disable-swagger-default-url: true
    display-request-duration: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
  api-docs:
    path: /api-docs # openAPI 접근 경로
  show-actuator: true # Spring Actuator의 endpoint까지 노출할지 여부
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match: # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출
    - /api/**