name: Auto Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Push to NCP container registry
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4

      # JDK setting
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # secret yml file 생성
      - name: Set secret yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DATABASE_YML }}" | base64 --decode > src/main/resources/application-database.yml
          echo "${{ secrets.NAVER_TOKEN_YML }}" | base64 --decode > src/main/resources/application-naver-token.yml
          echo "${{ secrets.SECURITY_YML }}" | base64 --decode > src/main/resources/application-security.yml
          find src
        shell: bash

      # Gradle 권한 부여
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      # 테스트 없이 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker Buildx 설치
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
          docker build -t ${{ secrets.NCP_CONTAINER_REGISTRY }}/americanote_docker .
          docker push ${{ secrets.DOCKER_REPO }}/americanote_docker
          

  deploy:
    name: Connect server ssh and pull from container registry
    needs: build
    runs-on: ubuntu-latest

    # Access Server & Docker compose up
    steps:
      - name: Connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo docker rm -f $(docker ps -a -q)
            sudo docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/americanote_docker
            sudo docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/americanote_nginx
            docker-compose up -d
            docker image prune -f